# Generated by Django 6.0.2 on 2026-02-23 11:51

from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        TrigramExtension(),
    ]
