# Generated by Django 6.0.2 on 2026-03-18 07:57

import apps.common.utils.paths
import apps.common.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import pghistory.utils
import pgtrigger.compiler
import pgtrigger.migrations
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('role', models.CharField(choices=[('director', 'Директор'), ('sys_admin', 'Системный администратор'), ('chief_acc', 'Главный бухгалтер'), ('lead_acc', 'Ведущий бухгалтер'), ('accountant', 'Бухгалтер'), ('junior', 'Младший бухгалтер'), ('lawyer', 'Юрисконсульт'), ('hr', 'Специалист по кадрам'), ('it', 'IT-специалист'), ('security_guard', 'Охранник')], default='accountant', max_length=50, verbose_name='Роль')),
                ('employment_status', models.CharField(choices=[('full_time', 'В штате'), ('probation', 'Испытательный срок'), ('contractor', 'Подряд (договор подряда)'), ('part_time', 'Частичная занятость')], default='probation', max_length=20, verbose_name='Статус оформления')),
                ('probation_end_date', models.DateField(blank=True, help_text='Дата окончания испытательного срока', null=True, verbose_name='Конец испытательного срока')),
                ('contract_start_date', models.DateField(blank=True, help_text='Дата приема на работу или начала текущего контракта', null=True, verbose_name='Начало контракта')),
                ('contract_end_date', models.DateField(blank=True, help_text='Дата истечения срока действия контракта', null=True, verbose_name='Окончание контракта')),
                ('middle_name', models.CharField(blank=True, max_length=150, verbose_name='Отчество')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=apps.common.utils.paths.RandomFileName('users/avatars'), validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png']), apps.common.validators.FileSizeValidator(max_size_mb=5)], verbose_name='Фото')),
                ('phone', models.CharField(blank=True, max_length=30, validators=[apps.common.validators.validate_international_phone_number], verbose_name='Телефон')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('bio', models.TextField(blank=True, help_text='Краткая информация, навыки, хобби', verbose_name='О себе')),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True, verbose_name='Дата удаления')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Название')),
                ('head', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_department', to=settings.AUTH_USER_MODEL, verbose_name='Начальник отдела')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_departments', to='users.department', verbose_name='Родительский отдел')),
            ],
            options={
                'verbose_name': 'Отдел',
                'verbose_name_plural': 'Отделы',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='users.department', verbose_name='Отдел'),
        ),
        migrations.CreateModel(
            name='UserEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('pgh_context', pghistory.utils.JSONField(null=True)),
                ('pgh_context_id', models.UUIDField(null=True)),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('role', models.CharField(choices=[('director', 'Директор'), ('sys_admin', 'Системный администратор'), ('chief_acc', 'Главный бухгалтер'), ('lead_acc', 'Ведущий бухгалтер'), ('accountant', 'Бухгалтер'), ('junior', 'Младший бухгалтер'), ('lawyer', 'Юрисконсульт'), ('hr', 'Специалист по кадрам'), ('it', 'IT-специалист'), ('security_guard', 'Охранник')], default='accountant', max_length=50, verbose_name='Роль')),
                ('employment_status', models.CharField(choices=[('full_time', 'В штате'), ('probation', 'Испытательный срок'), ('contractor', 'Подряд (договор подряда)'), ('part_time', 'Частичная занятость')], default='probation', max_length=20, verbose_name='Статус оформления')),
                ('probation_end_date', models.DateField(blank=True, help_text='Дата окончания испытательного срока', null=True, verbose_name='Конец испытательного срока')),
                ('contract_start_date', models.DateField(blank=True, help_text='Дата приема на работу или начала текущего контракта', null=True, verbose_name='Начало контракта')),
                ('contract_end_date', models.DateField(blank=True, help_text='Дата истечения срока действия контракта', null=True, verbose_name='Окончание контракта')),
                ('middle_name', models.CharField(blank=True, max_length=150, verbose_name='Отчество')),
                ('department', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='users.department', verbose_name='Отдел')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='user',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "users_userevent" ("contract_end_date", "contract_start_date", "date_joined", "department_id", "email", "employment_status", "first_name", "id", "is_active", "is_staff", "is_superuser", "last_login", "last_name", "middle_name", "password", "pgh_context", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "probation_end_date", "role") VALUES (NEW."contract_end_date", NEW."contract_start_date", NEW."date_joined", NEW."department_id", NEW."email", NEW."employment_status", NEW."first_name", NEW."id", NEW."is_active", NEW."is_staff", NEW."is_superuser", NEW."last_login", NEW."last_name", NEW."middle_name", NEW."password", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_id\', TRUE), \'\'), NULL)::UUID, NOW(), \'insert\', NEW."id", NEW."probation_end_date", NEW."role"); RETURN NULL;', hash='738a345fc0891c03a1cffdbc30e8bee2e7fa8dec', operation='INSERT', pgid='pgtrigger_insert_insert_52e78', table='users_user', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='user',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "users_userevent" ("contract_end_date", "contract_start_date", "date_joined", "department_id", "email", "employment_status", "first_name", "id", "is_active", "is_staff", "is_superuser", "last_login", "last_name", "middle_name", "password", "pgh_context", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "probation_end_date", "role") VALUES (NEW."contract_end_date", NEW."contract_start_date", NEW."date_joined", NEW."department_id", NEW."email", NEW."employment_status", NEW."first_name", NEW."id", NEW."is_active", NEW."is_staff", NEW."is_superuser", NEW."last_login", NEW."last_name", NEW."middle_name", NEW."password", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_id\', TRUE), \'\'), NULL)::UUID, NOW(), \'update\', NEW."id", NEW."probation_end_date", NEW."role"); RETURN NULL;', hash='287615ef9cd099a06660310588788dd2a444b782', operation='UPDATE', pgid='pgtrigger_update_update_16e22', table='users_user', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='user',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "users_userevent" ("contract_end_date", "contract_start_date", "date_joined", "department_id", "email", "employment_status", "first_name", "id", "is_active", "is_staff", "is_superuser", "last_login", "last_name", "middle_name", "password", "pgh_context", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "probation_end_date", "role") VALUES (OLD."contract_end_date", OLD."contract_start_date", OLD."date_joined", OLD."department_id", OLD."email", OLD."employment_status", OLD."first_name", OLD."id", OLD."is_active", OLD."is_staff", OLD."is_superuser", OLD."last_login", OLD."last_name", OLD."middle_name", OLD."password", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_id\', TRUE), \'\'), NULL)::UUID, NOW(), \'delete\', OLD."id", OLD."probation_end_date", OLD."role"); RETURN NULL;', hash='fa0a6525b79427951afbefb5d0f768292b589e01', operation='DELETE', pgid='pgtrigger_delete_delete_56c96', table='users_user', when='AFTER')),
        ),
        migrations.AddIndex(
            model_name='userevent',
            index=models.Index(models.F('pgh_context__correlation_id'), name='user_pgh_corr_idx'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='userevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='147f21ffd56e65f8363f55068815758ec34d2613', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_6b2f3', table='users_userevent', when='BEFORE')),
        ),
    ]
