"""
Django settings for Kronon project.

Generated by 'django-admin startproject' using Django 6.0.1.
Enhanced for Enterprise Accounting System requirements
"""

import os
import sys
from datetime import timedelta
from pathlib import Path
from typing import Any

import environ
import sentry_sdk

# ==============================================================================
# ENVIRONMENT CONFIGURATION
# ==============================================================================

# Путь к корневой директории проекта
BASE_DIR = Path(__file__).resolve().parent.parent

# Добавляем 'apps' в системный путь, чтобы импортировать приложения как 'users.models' вместо 'apps.users.models'
sys.path.insert(0, os.path.join(BASE_DIR, "apps"))

# Инициализация обработки переменных окружения
env = environ.Env()

# Чтение .env файла (ищем .env файл в корне проекта)
READ_DOT_ENV_FILE = env.bool("DJANGO_READ_DOT_ENV_FILE", default=True)

if READ_DOT_ENV_FILE:
    env_file = BASE_DIR / ".env"

    if env_file.exists():
        environ.Env.read_env(env_file)


# ==============================================================================
# CORE SETTINGS
# ==============================================================================

# Секретный ключ для подписи сессий и токенов
SECRET_KEY = env("SECRET_KEY")

# debug-режим
DEBUG = env.bool("DEBUG", default=False)

# Список хостов, которым разрешено обращаться к приложению
ALLOWED_HOSTS: list[str] = env.list("ALLOWED_HOSTS", default=["localhost", "127.0.0.1"])

# --- Настройки прокси (Nginx) ---
# Если Django запущен за Nginx (в Docker), нужно доверять заголовкам прокси
if env.bool("USE_X_FORWARDED_HOST", default=True):
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    USE_X_FORWARDED_HOST = True
    USE_X_FORWARDED_PORT = True


# ==============================================================================
# APPLICATIONS
# ==============================================================================

INSTALLED_APPS = [
    # --- Встроенные приложения Django ---
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # --- Сторонние библиотеки ---
    "ninja",  # Быстрый API (FastAPI-like)
    "guardian",  # Объектные права доступа (Object Level Permissions)
    "axes",  # Защита от подбора паролей (brute-force protection)
    # "corsheaders",  # CORS (для React) TODO: раскомментировать при подключении фронта

    # --- Приложения проекта Kronon ---
    "apps.users",  # Пользователи, Отделы, Авторизация
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",  # Эффективная раздача статики
    "django.contrib.sessions.middleware.SessionMiddleware",
    # "corsheaders.middleware.CorsMiddleware",  # CORS (для React) TODO: раскомментировать при подключении фронта
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "axes.middleware.AxesMiddleware",  # Middleware безопасности Axes
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        # Ищем шаблоны в корневой папке 'templates' и внутри приложений
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# ==============================================================================
# DATABASE (PostgreSQL)
# ==============================================================================

# Сборка URL подключения к БД
_DB_NAME = env("DB_NAME", default="kronon_db")
_DB_USER = env("DB_USER", default="postgres")
_DB_PASSWORD = env("DB_PASSWORD", default="postgres")
_DB_HOST = env("DB_HOST", default="localhost") # 'db' для Docker, 'localhost' для локальной разработки
_DB_PORT = env("DB_PORT", default="5432")

DATABASES = {
    "default": env.db_url(
        "DATABASE_URL",
        default=f"postgres://{_DB_USER}:{_DB_PASSWORD}@{_DB_HOST}:{_DB_PORT}/{_DB_NAME}"
    )
}


# ==============================================================================
# CACHE (Redis)
# ==============================================================================

REDIS_HOST = env("REDIS_HOST", default="localhost")
REDIS_PORT = env.int("REDIS_PORT", default=6379)

# Явно аннотируем тип переменной CACHES для mypy (Strict mode)
CACHES: dict[str, Any]

# Проверка режима тестирования (`pytest` автоматически добавляет 'test' в `sys.argv`)
if "test" in sys.argv or env.bool("TESTING", default=False):
    # Если это тесты (pytest), используем DummyCache, чтобы не зависеть от Redis
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.dummy.DummyCache",
        }
    }
else:
    CACHES = {
        "default": {
            "BACKEND": "django_redis.cache.RedisCache",
            # Используем базу №1 для кэша (чтобы не пересекаться с Celery)
            "LOCATION": f"redis://{REDIS_HOST}:{REDIS_PORT}/1",
            "OPTIONS": {
                "CLIENT_CLASS": "django_redis.client.DefaultClient",
                # Игнорировать ошибки подключения (сайт будет работать, но медленнее)
                "IGNORE_EXCEPTIONS": True,
            },
        }
    }

# Время жизни кэша по умолчанию (10 минут)
CACHE_TTL = 60 * 10


# ==============================================================================
# ASYNCHRONOUS TASKS (Celery)
# ==============================================================================

# URL брокера (по умолчанию база №2 в Redis)
CELERY_BROKER_URL = env(
    "CELERY_BROKER_URL",
    default=f"redis://{REDIS_HOST}:{REDIS_PORT}/2"
)

# URL для хранения результатов выполнения задач (по умолчанию база №2 в Redis)
CELERY_RESULT_BACKEND = env(
    "CELERY_RESULT_BACKEND",
    default=f"redis://{REDIS_HOST}:{REDIS_PORT}/2"
)

CELERY_TIMEZONE = "Europe/Minsk"
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60  # Максимум 30 минут на задачу


# ==============================================================================
# AUTHENTICATION & SECURITY
# ==============================================================================

# Указываем Django использовать кастомную модель пользователя
AUTH_USER_MODEL = "users.User"

AUTHENTICATION_BACKENDS = [
    "axes.backends.AxesBackend",                  # Защита от перебора паролей
    "django.contrib.auth.backends.ModelBackend",  # Стандартный вход
    "guardian.backends.ObjectPermissionBackend",  # Объектные права
]

# Валидаторы паролей TODO: усилить для прода
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

# --- Настройки Axes ---
# Количество неудачных попыток до блокировки
AXES_FAILURE_LIMIT = 5

# Время "остывания" после блокировки (10 минут)
AXES_COOLOFF_TIME = timedelta(minutes=10)

# Блокируем по комбинации IP + Username
AXES_LOCKOUT_PARAMETERS = ["ip_address", "username"]

# Учитываем, что мы за Nginx (Reverse Proxy)
AXES_BEHIND_REVERSE_PROXY = True
AXES_REVERSE_PROXY_HEADER = "HTTP_X_FORWARDED_FOR"

# Логировать попытки входа в БД (полезно для аудита)
AXES_ENABLE_ACCESS_LOG = True


# ==============================================================================
# INTERNATIONALIZATION
# ==============================================================================

LANGUAGE_CODE = 'ru-ru'
TIME_ZONE = "Europe/Minsk"
USE_I18N = True
USE_TZ = True

# Форматы ввода даты (DD.MM.YYYY - стандарт в РБ)
DATE_INPUT_FORMATS = [
    "%d.%m.%Y",  # 25.10.2025
    "%Y-%m-%d",  # 2025-10-25 (ISO)
]

# ==============================================================================
# STATIC & MEDIA FILES
# ==============================================================================

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

# Директории для общих статических файлов (не внутри apps)
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# Whitenoise для сжатия и кэширования статики
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# Медиа файлы (загрузки пользователей: сканы, отчеты)
MEDIA_URL = "media/"
MEDIA_ROOT = BASE_DIR / "media"


# ==============================================================================
# LOGGING
# ==============================================================================

# Папка для логов
LOGS_DIR = BASE_DIR / "logs"
LOGS_DIR.mkdir(exist_ok=True)

LOG_LEVEL = env("LOG_LEVEL", default="INFO")
LOGFILE_SIZE = env.int("LOGFILE_SIZE", default=5) * 1024 * 1024
LOGFILE_COUNT = env.int("LOGFILE_COUNT", default=5)

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {module} {process:d} {thread:d} {message}",
            "style": "{",
        },
        "simple": {
            "format": "{levelname} {asctime} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
        "file": {
            "level": "INFO",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": LOGS_DIR / "django.log",
            "maxBytes": LOGFILE_SIZE,
            "backupCount": LOGFILE_COUNT,
            "formatter": "verbose",
        },
    },
    "root": {
        "handlers": ["console", "file"],
        "level": LOG_LEVEL,
    },
    "loggers": {
        "django": {
            "handlers": ["console", "file"],
            "level": LOG_LEVEL,
            "propagate": False,
        },
        # Отключаем лишний шум от сторонних библиотек
        "hpack": {"level": "WARNING"},
        "httpcore": {"level": "WARNING"},
    },
}
# TODO: Настроить Loguru (перехват стандартного logging) в __init__.py


# ==============================================================================
# MONITORING (Sentry)
# ==============================================================================

SENTRY_DSN = env("SENTRY_DSN", default=None)

if SENTRY_DSN and not DEBUG:
    sentry_sdk.init(
        dsn=SENTRY_DSN,
        traces_sample_rate=0.5,  # Сэмплирование 50% транзакций TODO: поставить 0.1 в проде
        send_default_pii=True,   # Отправка данных пользователя TODO: подумать о GDPR
        environment=env("SENTRY_ENVIRONMENT", default="production"),
    )


# ==============================================================================
# E-MAIL
# ==============================================================================

# E-mail настройки (Console для Dev, SMTP для Prod)
if DEBUG:
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
else:
    EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
    EMAIL_HOST = env("EMAIL_HOST", default="smtp.gmail.com")  # TODO: нужен реальный SMTP
    EMAIL_PORT = env.int("EMAIL_PORT", default=587)
    EMAIL_HOST_USER = env("EMAIL_HOST_USER", default="")
    EMAIL_HOST_PASSWORD = env("EMAIL_HOST_PASSWORD", default="")
    EMAIL_USE_TLS = env.bool("EMAIL_USE_TLS", default=True)

# E-mail отправителя по умолчанию
DEFAULT_FROM_EMAIL = env("DEFAULT_FROM_EMAIL", default="noreply@kronon.by")


# ==============================================================================
# OTHERS
# ==============================================================================

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Настройки для Guardian (анонимный пользователь не нужен)
ANONYMOUS_USER_NAME = None


