"""
Django settings for Kronon project.

Generated by 'django-admin startproject' using Django 6.0.1.
Enhanced for Enterprise Accounting System requirements
"""

import sys
from dataclasses import dataclass
from datetime import timedelta
from pathlib import Path
from typing import Any

import environ

# Импортируем функции настройки Loguru и Sentry
from config.core.logging import setup_loguru
from config.core.sentry import setup_sentry

# ==============================================================================
# ENVIRONMENT CONFIGURATION
# ==============================================================================

# Путь к корневой директории проекта
BASE_DIR = Path(__file__).resolve().parent.parent

# Инициализация обработки переменных окружения
env = environ.Env()

# Чтение .env файла (ищем .env файл в корне проекта)
READ_DOT_ENV_FILE: bool = env.bool("DJANGO_READ_DOT_ENV_FILE", default=True)

if READ_DOT_ENV_FILE:
    env_file = BASE_DIR / ".env"

    if env_file.exists():
        environ.Env.read_env(env_file)


# ==============================================================================
# CORE SETTINGS
# ==============================================================================

# Секретный ключ для подписи сессий и токенов
SECRET_KEY: str = env("SECRET_KEY")

# debug-режим
DEBUG: bool = env.bool("DEBUG", default=False)

# Список хостов, которым разрешено обращаться к приложению
ALLOWED_HOSTS: list[str] = env.list("ALLOWED_HOSTS", default=["localhost", "127.0.0.1"])

# --- CORS (Cross-Origin Resource Sharing) ---
# Список хостов фронтенда, которым разрешено обращаться к приложению (React на порту `5173`)
CORS_ALLOWED_ORIGINS: list[str] = env.list(
    "CORS_ALLOWED_ORIGINS",
    default=[
        "http://localhost:5173",
        "http://127.0.0.1:5173"
    ],
)
# Если нужно разрешить Cookie/Credentials (важно для авторизации)
CORS_ALLOW_CREDENTIALS: bool = True

# --- Настройки прокси (Nginx) ---
# Если Django запущен за Nginx (в Docker), нужно доверять заголовкам прокси
if env.bool("USE_X_FORWARDED_HOST", default=True):
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    USE_X_FORWARDED_HOST = True
    USE_X_FORWARDED_PORT = True


# ==============================================================================
# APPLICATIONS
# ==============================================================================

INSTALLED_APPS = [
    # --- Встроенные приложения Django ---
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # --- Сторонние библиотеки ---
    "ninja",  # Быстрый API (FastAPI-like)
    "guardian",  # Объектные права доступа (Object Level Permissions)
    "axes",  # Защита от подбора паролей (brute-force protection)
    "corsheaders",  # CORS (для React)

    # --- Приложения проекта Kronon ---
    "apps.users",  # Пользователи, Отделы, Авторизация
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",  # Эффективная раздача статики
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",  # Middleware для React
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "axes.middleware.AxesMiddleware",  # Middleware безопасности Axes
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        # Ищем шаблоны в корневой папке 'templates' и внутри приложений
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# ==============================================================================
# DATABASE (PostgreSQL)
# ==============================================================================

# Сборка URL подключения к БД
_DB_NAME: str = env("DB_NAME", default="kronon_db")
_DB_USER: str = env("DB_USER", default="postgres")
_DB_PASSWORD: str = env("DB_PASSWORD", default="postgres")
_DB_HOST: str = env("DB_HOST", default="db") # 'db' для Docker, 'localhost' для локальной разработки
_DB_PORT: int = env.int("DB_PORT", default=5432)

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": _DB_NAME,
        "USER": _DB_USER,
        "PASSWORD": _DB_PASSWORD,
        "HOST": _DB_HOST,
        "PORT": _DB_PORT,
    }
}


# ==============================================================================
# CACHE (Redis)
# ==============================================================================

REDIS_HOST: str = env("REDIS_HOST", default="localhost")
REDIS_PORT: int = env.int("REDIS_PORT", default=6379)

# Флаг запущены ли тесты (pytest)
TESTING: bool = "test" in sys.argv or any(arg.startswith("pytest") for arg in sys.argv)

# Явно аннотируем тип переменной CACHES для mypy (Strict mode)
CACHES: dict[str, Any]

if TESTING:
    # Если это тесты, используем DummyCache, чтобы не зависеть от Redis
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.dummy.DummyCache",
        }
    }
else:
    CACHES = {
        "default": {
            "BACKEND": "django_redis.cache.RedisCache",
            # Используем базу №1 для кэша (чтобы не пересекаться с Celery)
            "LOCATION": f"redis://{REDIS_HOST}:{REDIS_PORT}/1",
            "OPTIONS": {
                "CLIENT_CLASS": "django_redis.client.DefaultClient",
                # Игнорировать ошибки подключения (сайт будет работать, но медленнее)
                "IGNORE_EXCEPTIONS": True,
            },
        }
    }

# Время жизни кэша по умолчанию (10 минут)
CACHE_TTL = 60 * 10


# ==============================================================================
# AUTHENTICATION, SECURITY & CORS
# ==============================================================================

# Указываем Django использовать кастомную модель пользователя
AUTH_USER_MODEL = "users.User"

AUTHENTICATION_BACKENDS = [
    "axes.backends.AxesBackend",                  # Защита от перебора паролей
    "django.contrib.auth.backends.ModelBackend",  # Стандартный вход
    "guardian.backends.ObjectPermissionBackend",  # Объектные права
]

# Валидаторы паролей TODO: усилить для прода
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

# --- Настройки Axes ---
# Количество неудачных попыток до блокировки
AXES_FAILURE_LIMIT = 5
# Время "остывания" после блокировки (10 минут)
AXES_COOLOFF_TIME = timedelta(minutes=10)
# Блокируем по комбинации IP + Username
AXES_LOCKOUT_PARAMETERS = ["ip_address", "username"]
# Логировать попытки входа в БД (полезно для аудита)
AXES_ENABLE_ACCESS_LOG = True

# Если Axes будет неправильно определять IP (всегда 127.0.0.1), раскомментировать эту строку
# AXES_CLIENT_IP_CALLABLE = "axes.handlers.proxy.get_client_ip_address"


# ==============================================================================
# ASYNC TASKS (Celery)
# ==============================================================================

# URL брокера (по умолчанию база №2 в Redis)
CELERY_BROKER_URL: str = env(
    "CELERY_BROKER_URL",
    default=f"redis://{REDIS_HOST}:{REDIS_PORT}/2"
)

# URL для хранения результатов выполнения задач (по умолчанию база №2 в Redis)
CELERY_RESULT_BACKEND: str = env(
    "CELERY_RESULT_BACKEND",
    default=f"redis://{REDIS_HOST}:{REDIS_PORT}/2"
)

CELERY_TIMEZONE = "Europe/Minsk"
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60  # Максимум 30 минут на задачу


# ==============================================================================
# INTERNATIONALIZATION
# ==============================================================================

LANGUAGE_CODE = 'ru-ru'
TIME_ZONE = "Europe/Minsk"
USE_I18N = True
USE_TZ = True

# Форматы ввода даты (DD.MM.YYYY - стандарт в РБ)
DATE_INPUT_FORMATS = [
    "%d.%m.%Y",  # 25.10.2025
    "%Y-%m-%d",  # 2025-10-25 (ISO)
]

# ==============================================================================
# STATIC & MEDIA FILES
# ==============================================================================

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

# Директории для общих статических файлов (не внутри apps)
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# Whitenoise для сжатия и кэширования статики
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# Медиа файлы (загрузки пользователей: сканы, отчеты)
MEDIA_URL = "media/"
MEDIA_ROOT = BASE_DIR / "media"


# ==============================================================================
# E-MAIL
# ==============================================================================

# E-mail настройки (Console для Dev, SMTP для Prod)
if DEBUG:
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
else:
    EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
    EMAIL_HOST: str = env("EMAIL_HOST", default="smtp.gmail.com")  # TODO: нужен реальный SMTP
    EMAIL_PORT: int = env.int("EMAIL_PORT", default=587)
    EMAIL_HOST_USER: str = env("EMAIL_HOST_USER", default="")
    EMAIL_HOST_PASSWORD: str = env("EMAIL_HOST_PASSWORD", default="")
    EMAIL_USE_TLS: bool = env.bool("EMAIL_USE_TLS", default=True)

# E-mail отправителя по умолчанию
DEFAULT_FROM_EMAIL: str = env("DEFAULT_FROM_EMAIL", default="noreply@kronon.by")


# ==============================================================================
# OTHERS
# ==============================================================================

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Настройки для Guardian (анонимный пользователь не нужен)
ANONYMOUS_USER_NAME = None


# ==============================================================================
# INITIALIZATION (Logging & Sentry)
# ==============================================================================

@dataclass
class AppConfig:
    """
    Класс-контейнер, который собирает необходимые настройки
    и удовлетворяет протоколам LoggingSettings и SentrySettings.
    """
    # Общие
    BASE_DIR: Path = BASE_DIR
    DEBUG: bool  = DEBUG
    # Loguru
    LOG_LEVEL: str = env("LOG_LEVEL", default="INFO")
    LOGFILE_SIZE: int = env.int("LOGFILE_SIZE", default=10)
    LOGFILE_COUNT: int = env.int("LOGFILE_COUNT", default=5)
    # Sentry
    SENTRY_DSN: str = env("SENTRY_DSN", default=None)
    SENTRY_ENVIRONMENT: str = env("SENTRY_ENVIRONMENT", default="production")


# Инициализация класса настроек
_app_config = AppConfig()

# Инициализируем Loguru
setup_loguru(_app_config)

# Инициализируем Sentry
setup_sentry(_app_config)
