# Generated by Django 6.0.2 on 2026-03-16 09:29

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_install_trigram'),
        ('pghistory', '0007_auto_20250421_0444'),
    ]

    operations = [
        migrations.CreateModel(
            name='KrononEvents',
            fields=[
            ],
            options={
                'verbose_name': 'Журнал изменений',
                'verbose_name_plural': 'Журнал изменений',
                'ordering': ['-pgh_created_at'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('pghistory.events',),
            managers=[
                ('no_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
