# Generated by Django 6.0.2 on 2026-02-16 10:47

import apps.common.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True, verbose_name='Дата удаления')),
                ('name', models.CharField(db_index=True, help_text='Например: АБВ (для удобного поиска)', max_length=150, verbose_name='Краткое название')),
                ('full_legal_name', models.CharField(blank=True, help_text="Например: Общество с ограниченной ответственностью 'АБВ'", max_length=255, verbose_name='Полное юридическое название')),
                ('unp', models.CharField(db_index=True, max_length=9, unique=True, validators=[apps.common.validators.validate_unp], verbose_name='УНП')),
                ('org_type', models.CharField(choices=[('ip', 'ИП'), ('ooo', 'ООО'), ('odo', 'ОДО'), ('oao', 'ОАО'), ('zao', 'ЗАО'), ('chup', 'ЧУП'), ('fond', 'Фонд'), ('other', 'Другое')], default='ooo', max_length=10, verbose_name='Тип организации')),
                ('tax_system', models.CharField(choices=[('usn_no_nds', 'УСН без НДС (6%)'), ('usn_nds', 'УСН с НДС'), ('osn', 'Общая система налогообложения (ОСН)'), ('ip_ediny', 'Единый налог'), ('ip_podohodny', 'Подоходный налог (ОСН для ИП)'), ('npd', 'Налог на профессиональный доход (НПД)'), ('pvt', 'Парк высоких технологий (ПВТ)')], default='usn_no_nds', max_length=20, verbose_name='Система налогообложения')),
                ('status', models.CharField(choices=[('active', 'На обслуживании'), ('onboarding', 'Подключение (Договор)'), ('archived', 'Архив (Расторгнут)'), ('lead', 'Потенциальный')], db_index=True, default='onboarding', max_length=20, verbose_name='Статус')),
                ('contact_info', models.JSONField(blank=True, default=dict, verbose_name='Контактная информация')),
                ('google_folder_id', models.CharField(blank=True, help_text='ID папки, куда клиенты загружают первичку', max_length=100, verbose_name='ID папки Google Drive')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
    ]
