# Generated by Django 6.0.2 on 2026-02-26 14:24

import apps.common.validators
import pghistory.utils
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_install_trigram'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True, verbose_name='Дата удаления')),
                ('name', models.CharField(db_index=True, help_text='Например: АБВ (для удобного поиска)', max_length=150, verbose_name='Краткое название')),
                ('full_legal_name', models.CharField(blank=True, help_text="Например: Общество с ограниченной ответственностью 'АБВ'", max_length=255, verbose_name='Полное юридическое название')),
                ('unp', models.CharField(db_index=True, max_length=9, unique=True, validators=[apps.common.validators.validate_unp], verbose_name='УНП')),
                ('status', models.CharField(choices=[('active', 'На обслуживании'), ('onboarding', 'Подключение (Договор)'), ('archived', 'Архив (Расторгнут)'), ('lead', 'Потенциальный')], db_index=True, default='onboarding', max_length=20, verbose_name='Статус')),
                ('org_type', models.CharField(choices=[('ip', 'ИП'), ('ooo', 'ООО'), ('odo', 'ОДО'), ('oao', 'ОАО'), ('zao', 'ЗАО'), ('chup', 'ЧУП'), ('fond', 'Фонд'), ('other', 'Другое')], default='ooo', max_length=10, verbose_name='Тип организации')),
                ('tax_system', models.CharField(choices=[('usn_no_nds', 'УСН без НДС (6%)'), ('usn_nds', 'УСН с НДС'), ('osn', 'Общая система налогообложения (ОСН)'), ('ip_ediny', 'Единый налог'), ('ip_podohodny', 'Подоходный налог (ОСН для ИП)'), ('npd', 'Налог на профессиональный доход (НПД)'), ('pvt', 'Парк высоких технологий (ПВТ)')], default='usn_no_nds', max_length=20, verbose_name='Система налогообложения')),
                ('contact_info', models.JSONField(blank=True, default=dict, verbose_name='Контактная информация')),
                ('google_folder_id', models.CharField(blank=True, help_text='ID папки, куда клиенты загружают первичку', max_length=100, verbose_name='ID папки Google Drive')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='ClientEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('pgh_context', pghistory.utils.JSONField(null=True)),
                ('pgh_context_id', models.UUIDField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Дата удаления')),
                ('name', models.CharField(help_text='Например: АБВ (для удобного поиска)', max_length=150, verbose_name='Краткое название')),
                ('full_legal_name', models.CharField(blank=True, help_text="Например: Общество с ограниченной ответственностью 'АБВ'", max_length=255, verbose_name='Полное юридическое название')),
                ('unp', models.CharField(max_length=9, validators=[apps.common.validators.validate_unp], verbose_name='УНП')),
                ('status', models.CharField(choices=[('active', 'На обслуживании'), ('onboarding', 'Подключение (Договор)'), ('archived', 'Архив (Расторгнут)'), ('lead', 'Потенциальный')], default='onboarding', max_length=20, verbose_name='Статус')),
                ('org_type', models.CharField(choices=[('ip', 'ИП'), ('ooo', 'ООО'), ('odo', 'ОДО'), ('oao', 'ОАО'), ('zao', 'ЗАО'), ('chup', 'ЧУП'), ('fond', 'Фонд'), ('other', 'Другое')], default='ooo', max_length=10, verbose_name='Тип организации')),
                ('tax_system', models.CharField(choices=[('usn_no_nds', 'УСН без НДС (6%)'), ('usn_nds', 'УСН с НДС'), ('osn', 'Общая система налогообложения (ОСН)'), ('ip_ediny', 'Единый налог'), ('ip_podohodny', 'Подоходный налог (ОСН для ИП)'), ('npd', 'Налог на профессиональный доход (НПД)'), ('pvt', 'Парк высоких технологий (ПВТ)')], default='usn_no_nds', max_length=20, verbose_name='Система налогообложения')),
                ('contact_info', models.JSONField(blank=True, default=dict, verbose_name='Контактная информация')),
                ('google_folder_id', models.CharField(blank=True, help_text='ID папки, куда клиенты загружают первичку', max_length=100, verbose_name='ID папки Google Drive')),
                ('user_email', models.CharField(blank=True, max_length=254, null=True, verbose_name='Email пользователя (исторический)')),
                ('app_source', models.CharField(blank=True, max_length=50, null=True, verbose_name='Источник изменения')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Адрес')),
                ('method', models.CharField(blank=True, max_length=10, null=True, verbose_name='HTTP Метод')),
                ('url', models.TextField(blank=True, null=True, verbose_name='URL')),
                ('celery_task', models.CharField(blank=True, max_length=255, null=True, verbose_name='Celery Task')),
                ('command', models.CharField(blank=True, max_length=255, null=True, verbose_name='Команда')),
            ],
            options={
                'verbose_name': 'Журнал изменений клиента',
                'verbose_name_plural': 'Журнал изменений клиентов',
                'ordering': ['-pgh_created_at'],
            },
        ),
    ]
