# Generated by Django 6.0.2 on 2026-02-16 14:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='accountant',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['accountant', 'lead_acc', 'chief_acc']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients_accountant', to=settings.AUTH_USER_MODEL, verbose_name='Ведущий бухгалтер'),
        ),
        migrations.AddField(
            model_name='client',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Отдел, к которому приписан клиент', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='users.department', verbose_name='Обслуживающий отдел'),
        ),
        migrations.AddField(
            model_name='client',
            name='hr_specialist',
            field=models.ForeignKey(blank=True, help_text='Ответственный за кадровый учет (контракты, ПУ-1, ПУ-2 и т.д.)', limit_choices_to={'role': 'hr'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients_hr', to=settings.AUTH_USER_MODEL, verbose_name='Специалист по кадрам'),
        ),
        migrations.AddField(
            model_name='client',
            name='payroll_accountant',
            field=models.ForeignKey(blank=True, help_text='Если зарплату считает отдельный специалист', limit_choices_to={'role__in': ['junior', 'accountant', 'lead_acc']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients_payroll', to=settings.AUTH_USER_MODEL, verbose_name='Бухгалтер по заработной плате'),
        ),
        migrations.AddField(
            model_name='client',
            name='primary_accountant',
            field=models.ForeignKey(blank=True, help_text='Ввод накладных, банка, кассы', limit_choices_to={'role__in': ['junior', 'accountant', 'lead_acc']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients_primary', to=settings.AUTH_USER_MODEL, verbose_name='Бухгалтер по первичной документации'),
        ),
    ]
