# Generated by Django 6.0.2 on 2026-02-26 11:38

import django.contrib.postgres.indexes
import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('pghistory', '0007_auto_20250421_0444'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='accountant',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['accountant', 'lead_acc', 'chief_acc']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients_accountant', to=settings.AUTH_USER_MODEL, verbose_name='Ведущий бухгалтер'),
        ),
        migrations.AddField(
            model_name='client',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Отдел, к которому приписан клиент', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='users.department', verbose_name='Обслуживающий отдел'),
        ),
        migrations.AddField(
            model_name='client',
            name='hr_specialist',
            field=models.ForeignKey(blank=True, help_text='Ответственный за кадровый учет (контракты, ПУ-1, ПУ-2 и т.д.)', limit_choices_to={'role': 'hr'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients_hr', to=settings.AUTH_USER_MODEL, verbose_name='Специалист по кадрам'),
        ),
        migrations.AddField(
            model_name='client',
            name='payroll_accountant',
            field=models.ForeignKey(blank=True, help_text='Если зарплату считает отдельный специалист', limit_choices_to={'role__in': ['junior', 'accountant', 'lead_acc']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients_payroll', to=settings.AUTH_USER_MODEL, verbose_name='Бухгалтер по заработной плате'),
        ),
        migrations.AddField(
            model_name='client',
            name='primary_accountant',
            field=models.ForeignKey(blank=True, help_text='Ввод накладных, банка, кассы', limit_choices_to={'role__in': ['junior', 'accountant', 'lead_acc']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients_primary', to=settings.AUTH_USER_MODEL, verbose_name='Бухгалтер по первичной документации'),
        ),
        migrations.AddField(
            model_name='clientevent',
            name='accountant',
            field=models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'role__in': ['accountant', 'lead_acc', 'chief_acc']}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Ведущий бухгалтер'),
        ),
        migrations.AddField(
            model_name='clientevent',
            name='department',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Отдел, к которому приписан клиент', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='users.department', verbose_name='Обслуживающий отдел'),
        ),
        migrations.AddField(
            model_name='clientevent',
            name='hr_specialist',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Ответственный за кадровый учет (контракты, ПУ-1, ПУ-2 и т.д.)', limit_choices_to={'role': 'hr'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Специалист по кадрам'),
        ),
        migrations.AddField(
            model_name='clientevent',
            name='payroll_accountant',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Если зарплату считает отдельный специалист', limit_choices_to={'role__in': ['junior', 'accountant', 'lead_acc']}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Бухгалтер по заработной плате'),
        ),
        migrations.AddField(
            model_name='clientevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='clientevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='clients.client'),
        ),
        migrations.AddField(
            model_name='clientevent',
            name='primary_accountant',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Ввод накладных, банка, кассы', limit_choices_to={'role__in': ['junior', 'accountant', 'lead_acc']}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Бухгалтер по первичной документации'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name', 'full_legal_name', 'unp'], name='client_search_gin_trgm_idx', opclasses=['gin_trgm_ops', 'gin_trgm_ops', 'gin_trgm_ops']),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='client',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "clients_clientevent" ("accountant_id", "contact_info", "created_at", "deleted_at", "department_id", "full_legal_name", "google_folder_id", "hr_specialist_id", "id", "name", "org_type", "payroll_accountant_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "primary_accountant_id", "status", "tax_system", "unp", "updated_at") VALUES (NEW."accountant_id", NEW."contact_info", NEW."created_at", NEW."deleted_at", NEW."department_id", NEW."full_legal_name", NEW."google_folder_id", NEW."hr_specialist_id", NEW."id", NEW."name", NEW."org_type", NEW."payroll_accountant_id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."primary_accountant_id", NEW."status", NEW."tax_system", NEW."unp", NEW."updated_at"); RETURN NULL;', hash='72cb0ce02c29ec2cd55f2e8bfac0459d2ea07cd1', operation='INSERT', pgid='pgtrigger_insert_insert_a5391', table='clients_client', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='client',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "clients_clientevent" ("accountant_id", "contact_info", "created_at", "deleted_at", "department_id", "full_legal_name", "google_folder_id", "hr_specialist_id", "id", "name", "org_type", "payroll_accountant_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "primary_accountant_id", "status", "tax_system", "unp", "updated_at") VALUES (NEW."accountant_id", NEW."contact_info", NEW."created_at", NEW."deleted_at", NEW."department_id", NEW."full_legal_name", NEW."google_folder_id", NEW."hr_specialist_id", NEW."id", NEW."name", NEW."org_type", NEW."payroll_accountant_id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."primary_accountant_id", NEW."status", NEW."tax_system", NEW."unp", NEW."updated_at"); RETURN NULL;', hash='18cc5a4b1509d665c83d82212731f0508ec29dda', operation='UPDATE', pgid='pgtrigger_update_update_757e7', table='clients_client', when='AFTER')),
        ),
    ]
